steps:
    -
    # build the container image 
        name: gcr.io/cloud-builders/docker
        args:
            - build
            - '-t'
            - 'gcr.io/ind-coe/github-repo:$COMMIT_SHA'
            - .
     # push the container image to Container Registry       
    -
        name: gcr.io/cloud-builders/docker
        args:
            - push
            - 'gcr.io/ind-coe/github-repo:$COMMIT_SHA'
            
      # Deploy container image to Cloud Run      
    -
        name: gcr.io/cloud-builders/gcloud
        args:
            - functions
            - deploy
            - ca-cr-app
            - '--runtime'
            - python37
            - '--trigger-http'
            - '--allow-unauthenticated'
            - '--source=https://source.cloud.google.com/ind-coe/github_dt1947in_clocks/+/master:'
        dir: 'functions/autodeploy'
